# Generated by Django 4.1 on 2024-02-23 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('regra', models.CharField(max_length=100)),
                ('imagem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_abo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=2, verbose_name='Grupo ABO')),
                ('fator_rh', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='Fator RH')),
                ('data', models.DateField(default=datetime.date(2024, 2, 23))),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hemocentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes_hemocentro', models.CharField(max_length=9, verbose_name='Cadastro Nacional de Estabelecimento de Saúde')),
                ('unidade', models.CharField(choices=[('HEMOGO - Goiânia', 'HEMOGO - Goiânia'), ('HEMOGO - Ceres', 'HEMOGO - Ceres'), ('HEMOGO - Catalão', 'HEMOGO - Catalão'), ('HEMOGO - Rio Verde', 'HEMOGO - Rio Verde'), ('HEMOGO - Jataí', 'HEMOGO - Jataí'), ('UCT - Formosa', 'UCT - Formosa'), ('UCT - Iporá', 'UCT - Iporá'), ('UCT - Porangatu', 'UCT - Porangatu'), ('UCT - Quirinópolis', 'UCT - Quirinópolis')], default='indef', max_length=100, verbose_name='Unidade')),
                ('cod_ibge', models.CharField(default='000000', max_length=6, verbose_name='Código IBGE')),
                ('municipio', models.CharField(choices=[('Goiânia', 'Goiânia'), ('Ceres', 'Ceres'), ('Catalão', 'Catalão'), ('Rio Verde', 'Rio Verde'), ('Jataí', 'Jataí'), ('Formosa', 'Formosa'), ('Iporá', 'Iporá'), ('Porangatu', 'Porangatu'), ('Quirinópolis', 'Quirinópolis')], max_length=20, verbose_name='Município')),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hemovida', models.CharField(max_length=9, verbose_name='Identificador no sistema Hemovida')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('cns', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número do Cartão Nacional de Saúde')),
                ('num_ident', models.CharField(max_length=11, verbose_name='Número da Identidade')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField(default='1900-01-01')),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('grupo_abo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=2, verbose_name='Grupo ABO')),
                ('fator_rh', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='Fator RH')),
                ('telefone', models.CharField(max_length=15)),
                ('badges', models.ManyToManyField(to='doador.badge')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_doacao', models.DateField(default=datetime.date(2024, 2, 23))),
                ('dias_inapto', models.IntegerField(default=60)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doador.doador')),
            ],
        ),
    ]
