# Generated by Django 4.1 on 2023-11-28 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hemocentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes_hemocentro', models.CharField(max_length=9, verbose_name='Cadastro Nacional de Estabelecimento de Saúde')),
                ('municipio', models.CharField(choices=[('Goiânia', 'Goiânia'), ('Ceres', 'Ceres'), ('Catalão', 'Catalão'), ('Rio Verde', 'Rio Verde'), ('Jataí', 'Jataí'), ('Formosa', 'Formosa'), ('Iporá', 'Iporá'), ('Porangatu', 'Porangatu'), ('Quirinópolis', 'Quirinópolis')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='doacao',
            name='data_doacao',
            field=models.DateField(default=datetime.date(2023, 11, 28)),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data',
            field=models.DateField(default=datetime.date(2023, 11, 28)),
        ),
    ]
