# Generated by Django 4.1 on 2023-11-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0003_alter_doacao_data_doacao_alter_doador_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hemocentro',
            name='municipio',
            field=models.CharField(choices=[('Goiânia', 'Goiânia'), ('Ceres', 'Ceres'), ('Catalão', 'Catalão'), ('Rio Verde', 'Rio Verde'), ('Jataí', 'Jataí'), ('Formosa', 'Formosa'), ('Iporá', 'Iporá'), ('Porangatu', 'Porangatu'), ('Quirinópolis', 'Quirinópolis')], max_length=20, verbose_name='Município'),
        ),
    ]
