# Generated by Django 4.1 on 2023-11-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0004_alter_hemocentro_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemocentro',
            name='cod_ibge',
            field=models.CharField(default='500000', max_length=7, verbose_name='Código IBGE'),
        ),
        migrations.AddField(
            model_name='hemocentro',
            name='unidade',
            field=models.CharField(choices=[('HEMOGO - Goiânia', 'HEMOGO - Goiânia'), ('HEMOGO - Ceres', 'HEMOGO - Ceres'), ('HEMOGO - Catalão', 'HEMOGO - Catalão'), ('HEMOGO - Rio Verde', 'HEMOGO - Rio Verde'), ('HEMOGO - Jataí', 'HEMOGO - Jataí'), ('UCT - Formosa', 'UCT - Formosa'), ('UCT - Iporá', 'UCT - Iporá'), ('UCT - Porangatu', 'UCT - Porangatu'), ('UCT - Quirinópolis', 'UCT-Quirinópolis')], default='indef', max_length=100, verbose_name='Unidade'),
        ),
    ]
